/* Teams */
insert into teams (id, acronym, name) values (1, 'RMA', 'Real Madrid');
insert into teams (id, acronym, name) values (2, 'FCB', 'FC Barcelona');
insert into teams (id, acronym, name) values (3, 'PSG', 'Paris Saint-Germain FC');
insert into teams (id, acronym, name) values (4, 'FCB', 'Bayern Munich');
insert into teams (id, acronym, name) values (5, 'JNJ', 'Theradent');
insert into teams (id, acronym, name) values (6, 'HTZ', 'Allergy Rescue 1');
insert into teams (id, acronym, name) values (7, 'ZGH', 'BUSPIRONE HYDROCHLORIDE');
insert into teams (id, acronym, name) values (8, 'NRK', 'Fluoxetine');
insert into teams (id, acronym, name) values (9, 'KCO', 'LE TECHNIQ');
insert into teams (id, acronym, name) values (10, 'GFI', 'Malin and Goetz');
insert into teams (id, acronym, name) values (11, 'ACD', 'Atropine Sulfate');
insert into teams (id, acronym, name) values (12, 'YMP', 'Epinephrine');
insert into teams (id, acronym, name) values (13, 'AEX', 'Infants Silapap');
insert into teams (id, acronym, name) values (14, 'WSJ', 'TOURMANIUM BB');
insert into teams (id, acronym, name) values (15, 'IPA', 'MILK OF MAGNESIA CHERRY');
insert into teams (id, acronym, name) values (16, 'SPZ', 'Everyday Clean Dandruff');
insert into teams (id, acronym, name) values (17, 'ZCD', 'napoleon PERDIS FOUNDATION');
insert into teams (id, acronym, name) values (18, 'GYD', 'Ibuprofen IB');
insert into teams (id, acronym, name) values (19, 'BUQ', 'Losartan Potassium');
insert into teams (id, acronym, name) values (20, 'IWH', 'TPN Electrolytes');
/* Players */
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (1, 'Ale', 'Real Ramos', 'ale@atos.com', '2000-07-24', 111, 1);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (2, 'Kathie', 'Pagitt', 'kpagitt1@wiley.com', '1962-04-19', 107, 2);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (3, 'Ertha', 'Pellitt', 'epellitt2@nationalgeographic.com', '1938-12-24', 59, 3);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (4, 'Cody', 'Zuppa', 'czuppa3@unicef.org', '1959-01-29', 74, 2);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (5, 'Jennee', 'Limbert', 'jlimbert4@squidoo.com', '1933-02-07', 46, 1);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (6, 'Carolan', 'Duggan', 'cduggan5@engadget.com', '1912-09-04', 82, 3);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (7, 'Benetta', 'Scown', 'bscown6@jimdo.com', '1921-04-19', 80, 3);
insert into players (id, name, lastname, email, birthdate, jersey_number, team_id) values (8, 'Barrett', 'Demoge', 'bdemoge7@si.edu', '1918-12-26', 31, 2);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (9, 'Calhoun', 'Aiken', 'caiken8@posterous.com', '1906-04-03', 109);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (10, 'Andrej', 'Monan', 'amonan9@indiegogo.com', '2021-03-07', 85);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (11, 'Jaye', 'Trewin', 'jtrewina@yolasite.com', '1970-05-02', 34);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (12, 'Aurie', 'Ewles', 'aewlesb@topsy.com', '1925-10-07', 31);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (13, 'Flory', 'Soggee', 'fsoggeec@etsy.com', '1944-09-16', 4);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (14, 'Russ', 'Sorby', 'rsorbyd@myspace.com', '2014-12-19', 79);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (15, 'Dewitt', 'Runcie', 'drunciee@shutterfly.com', '1907-07-24', 97);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (16, 'Garey', 'Braunlein', 'gbraunleinf@apple.com', '1963-04-06', 94);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (17, 'Alvina', 'Gann', 'aganng@illinois.edu', '2009-01-20', 102);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (18, 'Gwenny', 'Kuschel', 'gkuschelh@illinois.edu', '1907-04-09', 81);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (19, 'Christabel', 'Guido', 'cguidoi@si.edu', '1992-08-20', 50);
insert into players (id, name, lastname, email, birthdate, jersey_number) values (20, 'Tris', 'Rabson', 'trabsonj@walmart.com', '1928-07-25', 104);
/* Users */
insert into users (user_id, email, name, password) values ('1', 'ale@atos.com', 'ale', '$2a$10$88nmD1ZktNme.NbZnnDvD.OtG3FE3vGzZK6fJX6Dx/sNO3ukDlsHi');